const data = [
  {
    "_id": 1,
    "name": "Assam Green Tea",
    "category": "Black Tea",
    "image": "images/1.avif",
    "price": 250,
    "description": "Strong and bold flavor with a malty taste, perfect for a robust cup of chai. Assam tea is a black tea named after Assam, India, the region of its production. It is manufactured specifically from the plant Camellia sinensis var.",
    "rating": 4.8,
    "inStock": true,
    "origin": "Assam",
    "numberOfReviews": 520,
    "countInStock": 15
  },
  {
    "_id": 2,
    "name": "Darjeeling First Flush",
    "category": "Black Tea",
    "price": 450,
    "description": "Known as the 'Champagne of Teas', this tea has a delicate flavor with floral notes.",
    "rating": 3.7,
    "inStock": true,
    "origin": "Darjeeling",
    "image": "images/2.avif",
    "numberOfReviews": 95,
    "countInStock": 10
  },
  {
    "_id": 3,
    "name": "Masala Chai",
    "category": "Spiced Tea",
    "price": 150,
    "description": "A blend of black tea with spices like cardamom, ginger, and cinnamon, ideal for a flavorful chai.",
    "rating": 4.0,
    "inStock": true,
    "origin": "India",
    "image": "images/3.avif",
    "numberOfReviews": 230,
    "countInStock": 20
  },
  {
    "_id": 4,
    "name": "Green Tea",
    "category": "Green Tea",
    "price": 200,
    "description": "Light and refreshing, rich in antioxidants, suitable for a healthy lifestyle.",
    "rating": 3.6,
    "inStock": true,
    "origin": "India",
    "image": "images/4.avif",
    "numberOfReviews": 80,
    "countInStock": 18
  },
  {
    "_id": 5,
    "name": "Nilgiri Red Tea",
    "category": "White Tea",
    "price": 500,
    "description": "Delicate and smooth, with a subtle fruity flavor, sourced from the Nilgiri hills.",
    "rating": 3.0,
    "inStock": false,
    "origin": "Nilgiris",
    "image": "images/5.avif",
    "numberOfReviews": 45,
    "countInStock": 0
  },
  {
    "_id": 6,
    "name": "Tulsi Tea",
    "category": "Herbal Tea",
    "price": 180,
    "description": "An herbal tea made with holy basil leaves, known for its calming and immune-boosting properties.",
    "rating": 3.0,
    "inStock": false,
    "origin": "India",
    "image": "images/6.avif",
    "numberOfReviews": 150,
    "countInStock": 0
  },
  {
    "_id": 7,
    "name": "Oolong Tea",
    "category": "Oolong Tea",
    "price": 350,
    "description": "Partially fermented tea with a floral and slightly fruity flavor, often considered the perfect balance between green and black tea.",
    "rating": 4.2,
    "inStock": true,
    "origin": "Taiwan",
    "image": "images/7.avif",
    "numberOfReviews": 300,
    "countInStock": 12
  },
  {
    "_id": 8,
    "name": "Chamomile Tea",
    "category": "Herbal Tea",
    "price": 220,
    "description": "A soothing herbal tea made from dried chamomile flowers, known for its calming effects and mild, apple-like flavor.",
    "rating": 4.5,
    "inStock": true,
    "origin": "Egypt",
    "image": "images/8.avif",
    "numberOfReviews": 400,
    "countInStock": 25
  },
  {
    "_id": 9,
    "name": "Jasmine Green Tea",
    "category": "Green Tea",
    "price": 280,
    "description": "A fragrant green tea infused with jasmine flowers, known for its floral aroma and refreshing taste.",
    "rating": 4.3,
    "inStock": true,
    "origin": "China",
    "image": "images/9.avif",
    "numberOfReviews": 350,
    "countInStock": 30
  },
  {
    "_id": 10,
    "name": "Lemon Ginger Tea",
    "category": "Herbal Tea",
    "price": 170,
    "description": "A refreshing herbal blend of lemon and ginger, known for its detoxifying and digestive benefits.",
    "rating": 4.1,
    "inStock": true,
    "origin": "India",
    "image": "images/10.avif",
    "numberOfReviews": 290,
    "countInStock": 22
  },
  {
    "_id": 11,
    "name": "Mint Tea",
    "category": "Herbal Tea",
    "price": 160,
    "description": "A refreshing herbal tea made from fresh mint leaves, perfect for digestion and relaxation.",
    "rating": 4.6,
    "inStock": true,
    "origin": "Morocco",
    "image": "images/11.avif",
    "numberOfReviews": 200,
    "countInStock": 17
  },
  {
    "_id": 12,
    "name": "Earl Grey Tea",
    "category": "Black Tea",
    "price": 330,
    "description": "A black tea flavored with oil of bergamot, giving it a unique and fragrant citrusy aroma.",
    "rating": 4.7,
    "inStock": true,
    "origin": "England",
    "image": "images/12.avif",
    "numberOfReviews": 500,
    "countInStock": 0
  }
];

export default data;